name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - name: Install fonts
        run: sudo apt install fonts-noto fonts-noto-cjk fonts-noto-cjk-extra
      - uses: typst-community/setup-typst@v3
      - run: |
          mkdir ./out
          typst compile ./main.typ ./out/main.pdf
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./out
      - uses: actions/deploy-pages@v1
        id: deployment
